<?php

declare(strict_types=1);

namespace Semitexa\Demo\Application\Handler\PayloadHandler\GetStarted;

use Semitexa\Core\Attributes\AsPayloadHandler;
use Semitexa\Core\Attributes\InjectAsReadonly;
use Semitexa\Core\Contract\TypedHandlerInterface;
use Semitexa\Demo\Application\Payload\Request\GetStarted\InstallationPayload;
use Semitexa\Demo\Application\Resource\Response\DemoFeatureResource;
use Semitexa\Demo\Application\Service\DemoCatalogService;

#[AsPayloadHandler(payload: InstallationPayload::class, resource: DemoFeatureResource::class)]
final class InstallationHandler implements TypedHandlerInterface
{
    #[InjectAsReadonly]
    protected DemoCatalogService $catalog;

    public function handle(InstallationPayload $payload, DemoFeatureResource $resource): DemoFeatureResource
    {
        $explanation = [
            'what' => 'Installation is not only about getting files on disk. In Semitexa it should end with a running Docker-backed runtime, a clean operator shell, and enough introspection to trust the project shape immediately.',
            'how' => 'The installer scaffolds the project, writes `.env.default` as the committed baseline, keeps `.env.local` for machine-specific overrides only, and hands runtime control to `bin/semitexa` for boot, verification, and inspection.',
            'why' => 'If the first boot path is ambiguous, every later problem becomes harder to diagnose. The goal here is to standardize the first hour so the rest of the framework feels mechanical instead of improvised.',
            'keywords' => [
                ['term' => 'install.sh', 'definition' => 'The canonical one-line installer for creating a Semitexa project scaffold.'],
                ['term' => 'bin/semitexa', 'definition' => 'The operator shell for starting, stopping, inspecting, and validating the local runtime.'],
                ['term' => '.env.default', 'definition' => 'The committed local baseline generated by the installer. Review it, but do not treat it as a machine-specific scratch file.'],
                ['term' => '.env.local', 'definition' => 'Optional machine-specific overrides. Create it only when this workstation needs values different from the shared baseline.'],
                ['term' => 'self-test', 'definition' => 'A quick runtime health check for local setup validation.'],
                ['term' => 'routes:list', 'definition' => 'CLI command that prints discovered routes so the project shape is inspectable immediately after boot.'],
            ],
        ];

        return $resource
            ->pageTitle('Installation — Semitexa Framework')
            ->withDemoShellContext([
                'navSections' => $this->catalog->getSections(),
                'featureTree' => $this->catalog->getFeatureTree(),
                'currentSection' => 'get-started',
                'currentSlug' => 'installation',
                'infoWhat' => $explanation['what'],
                'infoHow' => null,
                'infoWhy' => null,
                'infoKeywords' => $explanation['keywords'],
            ])
            ->withSection('get-started')
            ->withSectionLabel('Get Started')
            ->withSlug('installation')
            ->withTitle('Installation')
            ->withSummary('Create the project, review the baseline env contract, and bring up the Semitexa runtime the supported way.')
            ->withEntryLine('The first useful Semitexa experience should end with a running app and an operator shell you can trust, not with a half-finished checklist.')
            ->withHighlights(['install.sh', '.env.default', '.env.local', 'bin/semitexa', 'self-test', 'routes:list'])
            ->withLearnMoreLabel('See the installation flow →')
            ->withDeepDiveLabel('What to verify after boot →')
            ->withResultPreviewTemplate('@project-layouts-semitexa-demo/components/previews/get-started-playbook.html.twig', [
                'eyebrow' => 'Canonical Install',
                'title' => 'Create the project and get to a trustworthy first boot',
                'summary' => 'Use the installer, review the shared env baseline, boot the runtime with the Semitexa CLI, and verify the project shape before you start authoring modules.',
                'steps' => [
                    [
                        'eyebrow' => 'Step 1',
                        'title' => 'Run the installer',
                        'summary' => 'The supported install path is the one-line installer. Use the named-directory form only when you want a specific folder immediately.',
                        'commands' => [
                            'curl -fsSL https://semitexa.com/install.sh | bash',
                            'curl -fsSL https://semitexa.com/install.sh | bash -s my-project',
                        ],
                    ],
                    [
                        'eyebrow' => 'Step 2',
                        'title' => 'Review the env boundary',
                        'summary' => 'Semitexa now writes `.env.default` as the committed baseline. Create `.env.local` only when this machine needs overrides such as a different port.',
                        'commands' => [
                            'cd my-project',
                            '$EDITOR .env.local',
                        ],
                    ],
                    [
                        'eyebrow' => 'Step 3',
                        'title' => 'Boot and verify',
                        'summary' => 'Use the operator shell to start, check, and inspect the runtime instead of guessing from container state alone. After boot, open the local app in the browser and confirm you have a real page, not just a running container.',
                        'commands' => [
                            'bin/semitexa server:start',
                            'bin/semitexa self-test',
                            'bin/semitexa routes:list --json',
                        ],
                    ],
                ],
                'callout' => [
                    'eyebrow' => 'Default Runtime',
                    'rules' => [
                        'Semitexa uses Docker as the supported local runtime boundary.',
                        'The default app URL is http://localhost:9502 unless `SWOOLE_PORT` is overridden in `.env.local`.',
                        'If you installed Semitexa Demo during setup, open http://localhost:9502/demo after boot to inspect working feature pages immediately.',
                        'You do not need host PHP or Composer for the normal local flow.',
                    ],
                ],
            ])
            ->withL2ContentTemplate('@project-layouts-semitexa-demo/components/previews/checklist-panel.html.twig', [
                'eyebrow' => 'Right After Install',
                'title' => 'Do these checks before you touch business code',
                'summary' => 'A clean first boot should be operationally legible. Use the CLI to confirm health, discovery, and current bindings before you start extending the project.',
                'rules' => [
                    'Run `bin/semitexa self-test` when startup feels suspicious instead of debugging blind.',
                    'Use `bin/semitexa logs:errors` as the first log command when the runtime did not boot cleanly.',
                    'Inspect `bin/semitexa describe:project --json` and `bin/semitexa contracts:list --json` early so you know what the project discovered.',
                    'If ORM-backed modules are active, treat `bin/semitexa orm:sync --dry-run` as part of the normal first setup path.',
                ],
            ])
            ->withL3ContentTemplate('@project-layouts-semitexa-demo/components/previews/checklist-panel.html.twig', [
                'eyebrow' => 'Boot Verification',
                'title' => 'What a clean first boot should prove',
                'summary' => 'After `bin/semitexa server:start`, you should be able to verify the runtime from both the browser and the operator shell without guessing what happened.',
                'rules' => [
                    'Open `http://localhost:9502` and confirm the app responds with the starter page instead of a Docker, proxy, or browser error.',
                    'If Semitexa Demo was installed, open `http://localhost:9502/demo` and confirm the demo home renders before you explore deeper pages.',
                    'Run `bin/semitexa self-test` and expect a clean health check before you start debugging application code.',
                    'Run `bin/semitexa routes:list --json` so route discovery is visible instead of assumed.',
                    'Use `bin/semitexa describe:project --json` when you need to inspect what the scaffold and installed modules actually registered.',
                ],
            ])
            ->withExplanation($explanation);
    }
}
